### ISSUE TITLE
reversed output devices 

### ISSUE THREAD

**Issue by Dan06567** [rtd1250/a70q_OTA#1]
I don't want to be repetitive, but as happens on Lineage 19.1, but internet calls like whatsapp, output devices are reversed. And sometimes when I use bluetooth headphones, the audio doesn't come through. This does not happen on SIM calls

**Comment by rtd1250** [comment]
Known issue since samsung audio swap, likely won't fix. If you need to report bugs on github instead of xda, at least do it on the development repo, not here.
