### ISSUE TITLE
How to enable NFC?

### ISSUE THREAD

**Issue by brownfox2k6** [rtd1250/a70q_OTA#10]
I cannot enable it here,

![Screenshot_20231124-123009_Settings.png](https://github.com/rtd1250/a70q_OTA/assets/111218756/a2e36ce5-f837-4497-a5d5-0b98e42ffdaf)

and, there is no way to turn on nfc service.

![Screenshot_20231124-123223_Settings.png](https://github.com/rtd1250/a70q_OTA/assets/111218756/f259f2ac-fcc6-41c5-95f8-b907a2a835b1)

**Comment by rtd1250** [comment]
What rom and version?

**Comment by brownfox2k6** [comment]
I'm using this version [lineage-20.0-20231031-UNOFFICIAL-a70q](https://github.com/rtd1250/a70q_OTA/releases/tag/20231031)

**Comment by brownfox2k6** [comment]
hello, I have installed LineageOS 21 but this feature is still not available.

**Comment by rtd1250** [comment]
without logs I can't do anything, especially since it works on my model, it sounds like a problem specific to some other a70 model

**Comment by brownfox2k6** [comment]
how do I send you my logs?

**Comment by rtd1250** [comment]
https://wiki.lineageos.org/how-to/logcat/

Of course capture the log after entering NFC settings (and optionally trying to enable NFC)

**Comment by rtd1250** [comment]
Since I haven't gotten any response, may I at least ask what model is your phone?

**Comment by brownfox2k6** [comment]
Sorry, my phone doesn't appear anything for me to trust my PC
![image](https://github.com/rtd1250/a70q_OTA/assets/111218756/17881e69-f345-4d61-8499-0049b48f3f5a)
My phone model is SM-A705F

**Comment by brownfox2k6** [comment]
I remember I was able to work with adb on your LineageOS 20, but not 21 (both 2 builds)

**Comment by rtd1250** [comment]
ADB forks fine for me and others, it's something on your end.

**Comment by brownfox2k6** [comment]
https://drive.google.com/file/d/1UKboYgkEa98bUJyusPJWwia5bURK6wVW/view?usp=sharing

hello, this is my log

**Comment by rtd1250** [comment]
There are communication errors, are you sure your phone does actually have NFC hardware? Not all A70 had this available and if your phone lacks support there's nothing I can do.
*I can also confirm NFC does work on the phones that support it, backed by several testers

**Comment by brownfox2k6** [comment]
Ok. Sorry for bothering you
