### ISSUE TITLE
Visual bug when changing the volume

### ISSUE THREAD

**Issue by brownfox2k6** [rtd1250/a70q_OTA#11]
https://github.com/rtd1250/a70q_OTA/assets/111218756/805ae003-e1f8-47ef-9808-f848b21dae12

However, it works perfectly in landscape mode.

**Comment by rtd1250** [comment]
I've seen this bug happen on many devices so I doubt it's device specific. Still, I'll keep this open for the time being just in case something changes

**Comment by rtd1250** [comment]
Should be fine with the latest builds.
