### ISSUE TITLE
wifi/LTE connecting but not working

### ISSUE THREAD

**Issue by amirali192** [rtd1250/a70q_OTA#14]
device : Samsung galaxy a70q

lineage OS 21 android 14

so after i installed lineage OS on my galaxy a70 everything was going perfectly fine until i noticed i cannot search in google because im not connected to the internet even thought i am

it kept saying limited connection even thought everything was fine on my other phone

i also tested if i can go into my router with [192.168.1.1](http://192.168.1.1/) and it worked but i cant use anything else

i also used some help from this reddit post https://www.reddit.com/r/LineageOS/comments/1avr2v4/wifi_stopped_working_after_upgrading_to_lineageos/

i used these commands :

adb root ; adb shell "rm -rf /data/misc/apexdata/com.android.wifi ; reboot"

adb root

adb shell

cd /data/vendor/wifi

restorecon -RFv /data/vendor/wifi

reboot

but still nothing was working

so i just factory reset my phone

help would be VERY appreciated since it took me a very long time and this is my first custom ROM

thanks

**Comment by rtd1250** [comment]
Make sure you have the latest stock firmware installed before attempting to install a custom ROM.
