### ISSUE TITLE
Error : 21 while installing the rom Galaxy a70FN

### ISSUE THREAD

**Issue by so5s** [rtd1250/a70q_OTA#15]
i keep getting this error when i try to install the rom file

**Comment by so5s** [comment]
lineage OS 21 android 14

**Comment by rtd1250** [comment]
Make sure to
- use latest LineageOS recovery (NOT twrp)
- format data before installing

**Comment by so5s** [comment]
yeah, i used the latest and got this error in odin 

<ID:0/005> Odin engine v(ID:3.1401)..
<ID:0/005> File analysis..
<ID:0/005> Total Binary size: 78 M
<ID:0/005> SetupConnection..
<ID:0/005> Initialzation..
<ID:0/005> Get PIT for mapping..
<ID:0/005> Firmware update start..
<ID:0/005> NAND Write Start!! 
<ID:0/005> SingleDownload.
<ID:0/005> ._recovery.img
<ID:0/005> Unassigned file
<ID:0/005> Complete(Write) operation failed.
<OSM> All threads completed. (succeed 0 / failed 1)

**Comment by so5s** [comment]
in option center the auto reboot and the reset time is marked by default, should i enable or disable something ?

**Comment by rtd1250** [comment]
Try flashing the previous version of lineage recovery, I'll double check the latest one later. Odin probably doesn't like it.

**Comment by so5s** [comment]
with the previous version of the ZIP file also right ?

**Comment by rtd1250** [comment]
zip can be latest, doesn't matter as you'll be able to update it later

**Comment by so5s** [comment]
oh, forgot to tell you it worked. thanks and keep up the good work

**Comment by so5s** [comment]
yeah i also noticed goverment apps and bank apps dont work here is that normal in any custom OS?
