### ISSUE TITLE
Iluminação da tela

### ISSUE THREAD

**Issue by JaderFarinon** [rtd1250/a70q_OTA#4]
Sistema ajusta de forma incorreta a luz de fundo da tela quando exibe a solicitação de biometria, geralmente a tela fica bem escura mesmo estando ajustada para brilho máximo, basta tocar na barra de ajuste do brilho para que o brilho retorne ao normal
([PixelExperience_Plus_a70q-13.0-20230302-2000-UNOFFICIAL])

**Comment by RubenPX** [comment]
Same here

**Comment by rtd1250** [comment]
fixed
