### ISSUE TITLE
"Tap animation" is missing in apps after the last update

### ISSUE THREAD

**Issue by quintus3236** [rtd1250/a70q_OTA#6]

**Comment by rtd1250** [comment]
Haven't noticed this anywhere. A more detailed description would be helpful.

**Comment by quintus3236** [comment]
Alright so this is how it's supposed to look and it does look like this in settings and quick panel

https://github.com/rtd1250/a70q_OTA/assets/119014876/ec1dd864-acaf-4647-888f-bf3c1ac5b358


But it looks wrong in pretty much everywhere except those two.


https://github.com/rtd1250/a70q_OTA/assets/119014876/5c842c29-67cf-44ea-a86f-74a59fee794d

**Comment by rtd1250** [comment]
Thank you for clarifying. Before, I've only seen bugged tap animations in roms other than Lineage, and that included the material apps such as Settings too. It does not look like a device-specific issue and will likely be solved upstream soon.

**Comment by rtd1250** [comment]
LGTM in the latest build.
