### ISSUE TITLE
my phone bricked after updating linageos via ota

### ISSUE THREAD

**Issue by brownfox2k6** [rtd1250/a70q_OTA#7]

**Comment by rtd1250** [comment]
That's not very descriptive. If you had google apps or magisk then it's very likely those are the culprit, so try reflashing them (or in case of magisk, go into safe mode).
Side note: always OTA update with lineage recovery, never use TWRP.

**Comment by brownfox2k6** [comment]
yes you're right, i'm using twrp. How do I install lineage recovery? Thank you.

**Comment by rtd1250** [comment]
Refer to installation guide here:
https://forum.xda-developers.com/t/rom-13-unofficial-stable-lineageos-20.4521107/

Download recovery, and using Odin flash it using AP button

**Comment by brownfox2k6** [comment]
Thank you, if I use Lineage Recovery, can I use OTA update if I have google apps and magisk? If not, what can I use instead of them?

**Comment by rtd1250** [comment]
No guarantees since it depends on your particular setup. For using Google's apps a rom like PixelExperience would probably fit better.

**Comment by brownfox2k6** [comment]
thank you I got it.
