### ISSUE TITLE
Ps4 controller not working 

### ISSUE THREAD

**Issue by Real-Segunfunmi** [rtd1250/a70q_OTA#9]
I've tested all roms here, the latest ones actually and none of them seem to be working with the ps4 controller... Gaming is a big part of why I joined the community of custom roms users and I use the controller all the time, I can't even play Cod without it. Please look into this, I would appreciate a fix in any of these roms

**Comment by rtd1250** [comment]
I don't have a DualShock 4 so I can't test it, however I've tested an Xbox controller over Bluetooth and a DualShock 3 over USB and both worked perfectly fine. Try using your controller over USB. I'll keep this issue in mind too.

**Comment by Real-Segunfunmi** [comment]
That would be great, thank you so much. It would connect but it just won't work

**Comment by rtd1250** [comment]
I've tested a PS4 controller, it does get detected and works perfectly over Bluetooth. All buttons work, including the joysticks - see attachment. Something could be wrong with your game or maybe the controller.
![Screenshot_20231109-231417](https://github.com/rtd1250/a70q_OTA/assets/47224354/9bc38a39-43cf-44f5-a310-4f99d997a3ba)
